### ISSUE TITLE
Best Practices

### ISSUE THREAD

**Issue by ryanmc2033** [TomBZombie/Dice#43]
I am just getting started with Dice and I have some questions about best practices. In our Stack we are using Tonic for our REST endpoints, and Doctrine as our ORM. These two programs have presented some problems with how I implemet Dice and I am trying to work around them.

First Tonic (https://github.com/peej/tonic). The way it is designed to handle DI is by adding the container to its application object  which it passes to the endpoints. Here is an example of how I have implemented it.

```
    $app = new Tonic\Application();
    $app ->di_container = new \Dice\Dice;
    
    $request = new Tonic\Request();
    $resource = $app->getResource($request);

    $response = $resource->exec();
```

and on the endpoint it looks like this

```
public function __construct(Application $app, Request $request)
    {
        $this->user_service = $app->di_container->create('namespace\UserService');
        $this->profile_service = $app->di_container->create('namespace\ProfileService');
        ...
    }
```

Does this seem like the best way? This could end up being a decent list because we do access Doctrine entities here and as I explain below we have a lot of Doctrine entities.

Now Doctrine (http://www.doctrine-project.org/). Doctrine creates an entity and manager for each table in our database. So if I have 10 tables Doctrine creates 20 classes. If I have a class that needs to use 5 of those tables I have to list 10 classes in my constructor.

```
   public function __construct(
        UserManager $user_manager,
        UserEntity $user_entity,
        ProfileManager $profile_manager,
        ProfileEntity $profile_entity,
        TestManager $test_manager,
        TestEntity $test_entity,
        CompanyManager $company_manager,
        CompanyEntity $company_entity,
        StateManager $state_manager,
        StateEntity $state_entity
    )
    {
        $this->user_manager = $user_manager;
        $this->user_entity = $user_entity;
        $this->profile_manager = $profile_manager;
        $this->profile_entity = $profile_entity;
        $this->test_manager = $test_manager;
        $this->test_entity = $test_entity;
        $this->company_manager = $company_manager;
        $this->company_entity = $company_entity;
        $this->state_manager = $state_manager;
        $this->state_entity = $state_entity;
    }
```

My concern is that this is going to become a really long list and a real big pain to maintain. 

I have thought of moving them all to a parent class that just defines all possible dependencies, but that seems like a bad idea. If Dice creates these objects in the constructor then that would cause a lot of unneeded classes to be put in memory. 

If I setup a shared rule for the classes then that might help, but I would have to maintain a huge list all my classes (around 100) just so I can assign them all a shared rule. Is there a way to have the classes be shared by default so I don't have to setup all the rules?

Anyways I could use a little direction on the best way to implement Dice. Otherwise I may just keep using our current method, which is a service locator that only creates classes when we need them and caches each class when it is created so that is does not take up a lot of memory.

```
public function getTestService()
    {
        if (empty($this->test_service)) {
            $this->test_service = new TestService();
        }
        return $this->test_service;
    }
```

**Comment by TomBZombie** [comment]
```php
public function __construct(Application $app, Request $request)
    {
        $this->user_service = $app->di_container->create('namespace\UserService');
        $this->profile_service = $app->di_container->create('namespace\ProfileService');
        ...
    }

```

This is a DI antipattern. It may be the best way to work around it in this scenario but Inversion of Control (Which is what we achieve via D) relies on the principle of least knowledge ( http://en.wikipedia.org/wiki/Law_of_Demeter ) and Tell, Don't Ask ( http://martinfowler.com/bliki/TellDontAsk.html )

Ideally, the above code should look like this:

```php
public function __construct(UserService $userService, ProfileService $profileService, Request $request)
    {
        $this->user_service = $userService;
        $this->profile_service = $profileService;
        ...
    }
```

Then move the creation of the UserService object up a level. If the reasoning for passing in $application rather than each dependency is that there are too many than feel comfortable in a constructor argument then it's highly likely a separation of concerns issue. See: http://misko.hevery.com/code-reviewers-guide/flaw-class-does-too-much/

Generally, if you're passing the DI container into anything other than a factory, you're doing it wrong. 
However, sometimes when working with poorly designed third party code it is difficult to work around these issues.

> I have thought of moving them all to a parent class that just defines all possible dependencies, but that seems like a bad idea. If Dice creates these objects in the constructor then that would cause a lot of unneeded classes to be put in memory.

I agree, this is basically turning the parent class into a service locator which is a very bad idea as it's inflexible and tightly couples everything to everything else.

```php
   public function __construct(
        UserManager $user_manager,
        UserEntity $user_entity,
        ProfileManager $profile_manager,
        ProfileEntity $profile_entity,
        TestManager $test_manager,
        TestEntity $test_entity,
        CompanyManager $company_manager,
        CompanyEntity $company_entity,
        StateManager $state_manager,
        StateEntity $state_entity
    )
    {
        $this->user_manager = $user_manager;
        $this->user_entity = $user_entity;
        $this->profile_manager = $profile_manager;
        $this->profile_entity = $profile_entity;
        $this->test_manager = $test_manager;
        $this->test_entity = $test_entity;
        $this->company_manager = $company_manager;
        $this->company_entity = $company_entity;
        $this->state_manager = $state_manager;
        $this->state_entity = $state_entity;
    }
```

Why do you need a manager and en entity for each of those? More importantly why does the class need so many in the first place? I'm not sure Dice can help you avoid this problem as it's not really a DI issue. Injecting each dependency really is the best way to go, there's probably an architectural adjustment that would help fix this but without knowing how the code works it's difficult to tell. At first glance it does make me think the class is probably doing too much ( http://misko.hevery.com/code-reviewers-guide/flaw-class-does-too-much/ ) although I may be wrong.

> If I setup a shared rule for the classes then that might help, but I would have to maintain a huge list all my classes (around 100) just so I can assign them all a shared rule. Is there a way to have the classes be shared by default so I don't have to setup all the rules?

If they all inherit from the same base class or interface, that's easy. Say there's an interface called "Entity", you can apply a rule to it:

```php

$rule = new \Dice\Rule;
$rule->shared = true;
$dice->addRule('Entity', $rule);
```

Any time a subclass of "Entity" is created it will be a shared instance. N.b. you can turn off this behaviour by setting `$rule->inherit` to `false`.

If they don't, you can set **all** objects to be shared by default by changing the default rule (*):

```php
$rule = new \Dice\Rule;
$rule->shared = true;
$dice->addRule('*', $rule);
```


Which will apply to *everything* created by Dice. Of course by doing this you will have to go through and flag any classes you don't want to be shared with `$rule->shared= false`

**Comment by ryanmc2033** [comment]
I tried re-factoring the code to start with dice like this 

```
$dice = new \Dice\Dice;

$app = $dice->create('Tonic\Application');
...
```

but when tonic instantiates a new endpoint it does it like this
```
return new $matchedResource[0]['class']($this, $request, $matchedResource[1]);
```

And I think that stops Dice from working with the rest of the code.

So where you say 
>Then move the creation of the UserService object up a level
this is what I did

```
$app = new Tonic\Application();

$dice = new \Dice\Dice;
$user_service = $dice->create('namespace\UserService');
$app ->di_container['user_service] = $user_service;
$profile_service = $dice->create('namespace\ProfileService');
$app ->di_container['profile_service ] = $profile_service ;
...

$request = new Tonic\Request();
$resource = $app->getResource($request);

$response = $resource->exec();
```

Then in the constructor of the endpoint I would do this 

```
public function __construct(Application $app, Request $request)
    {
        $this->user_service = $app->di_container['user_service'];
        $this->profile_service = $app->di_container['profile_service'];
        ...
    }
```

Is this better? The big downside is that I have to declare all the classes beforehand in case I need them later. That seems like it would eat up a lot of memory.

**Comment by TomBZombie** [comment]
> And I think that stops Dice from working with the rest of the code.

Ah, yes that will do it. You'll want to keep the original class unedited so you can get updates, so in this instance I would keep what you had originally and use

```php
public function __construct(Application $app, Request $request)
    {
        $this->user_service = $app->di_container->create('namespace\UserService');
        $this->profile_service = $app->di_container->create('namespace\ProfileService');
        ...
    }
```

It would be better if instead of a DI Container, Tonic accepted a closure for that and instead of:

```php
return new $matchedResource[0]['class']($this, $request, $matchedResource[1]);
```

it did something like:

```php
return $create($matchedResource[0]['class'], $this, $request, $matchedResource[1]);
```


Then someone could supply a closure:

```php
$create = function($className, $app, $request, $matchedResource) use ($dice) {
return $dice->create($className, [$app, $request, $matchedResource);
};
```

And then tonic wouldn't even need the di_container property. By default, $create could be set to:

```php
$create =  function($className, $app, $request, $matchedResource) {
    return new $matchedResource[0]['class']($app, $request, $matchedResource);
};
```

and the code would work as it does now.
