### ISSUE TITLE
How to add existing objects to a container?

### ISSUE THREAD

**Issue by burzum** [TomBZombie/Dice#75]
Sorry for asking that probably simple question, but how can I add an already existing object to the container?

My scenario is that I've implemented a custom service layer within my app written with the CakePHP framework and that I want to get the request and response objects in my dispatcher filter and want to add them there to the container.

I've wrapped a Dice instance with a singleton class to have a single, globally available container for some of the "global" classes. Cake is unfortunately not using any dependency injection but internally has a lot collections or loader methods for each kind of object.

**Comment by TomBZombie** [comment]
There's no way to assign an object directly to the container, however, you can add a global substitution rule:

```php
$object = new MyClass;

//Add a global rule by assigning it to *
$dice->addRule('*', ['substitutions' => 
                                                    ['MyClass' => $object]
                                ]);
```

Which will then use the `$object` instance as a substitution anywhere `MyClass` is type hinted:

```php

class Foo {
    public function __construct(MyClass $myclass) {}
}

$foo = $dice->create('Foo');
```

Which will now pass the substituted myclass instance rather than creating one on-the-fly.

**Comment by burzum** [comment]
That should work for me, thank you!
